package ch.dreipol.android.blinq.services.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.Date;

/**
 * Generated by http://www.jsonschema2pojo.org
 */
public class Match {

    @Expose
    private Profile profile;
    @Expose
    private Boolean received;
    @SerializedName("match_id")
    @Expose
    private Integer matchId;
    @SerializedName("created_at")
    @Expose
    private Date createdAt;
    @SerializedName("created_at_datetime")
    @Expose
    private Date createdAtDatetime;
    @SerializedName("fb_id")
    @Expose
    private String fbId;
    @Expose
    private Boolean blocked;

    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public Boolean getReceived() {
        return received;
    }

    public void setReceived(Boolean received) {
        this.received = received;
    }

    public Integer getMatchId() {
        return matchId;
    }

    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getCreatedAtDatetime() {
        return createdAtDatetime;
    }

    public void setCreatedAtDatetime(Date createdAtDatetime) {
        this.createdAtDatetime = createdAtDatetime;
    }

    public String getFbId() {
        return fbId;
    }

    public void setFbId(String fbId) {
        this.fbId = fbId;
    }

    public Boolean getBlocked() {
        return blocked;
    }

    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

}